spring:
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver

weather:
  base-url: ${weather.base-url}
  key: ${weather.key}
