spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db.changelog/changelog.yml
    user: ${LIQUIBASE_USER}
    password: ${LIQUIBASE_PASSWORD}
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}
          audiences: ${JWT_AUDIENCE}

weather:
  base-url: ${WEATHER_URL}
  key: ${WEATHER_KEY}
